name: "Cloning repo in env"
on: push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                    aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                    aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
                    aws-region: ${{secrets.AWS_DEFAULT_REGION}}
            - name: Create Security group
              run: |
                 aws ec2 create-security-group \
                 --group-name sgsumeetbgithubactions \
                 --description "Create security group"
                 --vpc-id vpc-08e5bc89ab4518ee3

            

        